Repository peerplays-network/peerplays-core-gui, pull requests merged in 2019-04, with the labels that each got.

#23 WAL-212: commitlint, commitizen, husky, standard-release, conventional-changelog.
  .huskyrc.json
  CHANGELOG.md
  README.md
  commitlint.config.js
  package-lock.json
  package.json
Labels: task

#22 WAL-206 wallet now properly reconnects after loss of connection
  package-lock.json
  src/actions/AppActions.js
  src/components/Modal/CantConnectModal/CantConnectModal.jsx
  src/services/AppService.js
  src/services/ChainStoreService.js
Labels: bug

#28 chore(release): 0.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: task

#10 Wal 145 use lowest latency node
  CHANGELOG.md
  config/Config.js
  package-lock.json
  package.json
  src/components/App/App.jsx
  src/components/SplashScreen/SplashScreen.jsx
  src/services/ConnectManager.js
Labels: story/feature

#29 refactor(app.jsx): update component import for splashscreen
  src/components/App/App.jsx
Labels: bug

#31 Wal 217
  .eslintrc
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  electron.js
  package-lock.json
  package.json
  public/index.html
  src/actions/DashboardPageActions.js
  src/actions/RAddressIndexActions.js
  src/actions/RWalletActions.js
  src/actions/RWalletDataActions.js
  src/actions/SendPageActions.js
  src/actions/VotingActions.js
  src/assets/images/images.js
  src/assets/loader.js
  src/assets/locales/locales.js
  src/chain/asset_constants.js
  src/common/filesaver.js
  src/components/ClaimBts/ClaimBtsContainer.jsx
  src/components/ClaimBts/ClaimBtsForm.jsx
  src/components/Dashboard/Balances/Balances.jsx
  src/components/Dashboard/Balances/Side.jsx
  src/components/Header/Header.jsx
  src/components/Help/HelpModal.jsx
  src/components/Login/LoginForm.jsx
  src/components/Modal/CantConnectModal/CantConnectModal.jsx
  src/components/Modal/TransactionConfirmModal/AccountUpdate.jsx
  src/components/Modal/TransactionConfirmModal/TransactionConfirmModal.jsx
  src/components/Register/RegisterForm.jsx
  src/components/Send/Send.jsx
  src/components/Settings/PermissionSettings.jsx
  src/components/Voting/CommitteeMembers.jsx
  src/components/Voting/Witnesses.jsx
  src/config/main.js
  src/constants/MessageLocation.js
  src/idb-helper.js
  src/reducers/AccountReducer.js
  src/reducers/AppReducer.js
  src/reducers/CommonMessageReducer.js
  src/reducers/DashboardPageReducer.js
  src/reducers/ExchangePageReducer.js
  src/reducers/ExplorerBlockchainPageReducer.js
  src/reducers/PageSettingsReducer.js
  src/reducers/SendPageReducer.js
  src/reducers/SettingsReducer.js
  src/reducers/TransactionConfirmReducer.js
  src/reducers/VotingReducer.js
  src/reducers/WalletDataReducer.js
  src/repositories/AccountRepository.js
  src/repositories/chain/repository.js
  src/services/AppService.js
  src/services/ChainStoreService.js
  src/services/ConnectManager.js
  src/services/DashboardBalancesService.js
  src/services/FormatOperation.js
  src/services/SendService.js
  src/services/ViewSettingsService.js
  src/services/WalletService.js
  src/store/configureStore.js
Labels: task

#32 fix: fix distributable crashing
  config/webpack.config.dev.js
  package.json
  public/index.html
Labels: bug

#33 refactor(ws): removed peerplaysjs-ws
  package-lock.json
  package.json
  src/actions/ChangePasswordActions.js
  src/actions/TransactionConfirmActions.js
  src/api/accountApi.js
  src/components/Wallet/rm/Backup.jsx
  src/components/Wallet/rm/BackupNew.jsx
  src/dl_cli_index.js
  src/idb-instance.js
  src/repositories/AccountRepository.js
  src/repositories/AssetRepository.js
  src/repositories/BalanceRepository.js
  src/repositories/BlocksRepository.js
  src/repositories/GlobalsRepository.js
  src/repositories/HistoryRepository.js
  src/repositories/MarketRepository.js
  src/repositories/ObjectRepository.js
  src/repositories/OrderRepository.js
  src/repositories/WitnessRepository.js
  src/repositories/chain/repository.js
  src/services/ConnectManager.js
  src/services/WalletService.js
  src/stores/AddressIndex.js
  src/stores/WalletDb.js
  src/stores/to_rm/AccountStore.js
  src/stores/to_rm/BalanceClaimActiveStore.js
Labels: task

#35 build(peerplaysjs-lib): use npm package
  package-lock.json
  package.json
Labels: task
